### ISSUE TITLE
Compile failed with build_kirisakura.sh

### ISSUE THREAD

**Issue by mxpro1996** [freak07/Kirisakura_OP7Pro_A11#1]
> Error about execvp

![IMG_20210517_200704](https://user-images.githubusercontent.com/73088482/118485887-8a8f2800-b74b-11eb-9ff6-84018d5436d6.jpg)

> Description

It's been fine before this error.

> Toolchain (branch android-11.0.0_r12)

[google-clang](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86) 
[arm-linux-androideabi-4.9](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9) 
[aarch64-linux-android-4.9](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9) 
[aosp-dtc](https://github.com/xzr467706992/dtc-aosp) 

> Config

```console
mkdir -p out 
export ARCH=arm64 
export SUBARCH=arm64
export CLANG_PATH=/root/google-clang/clang-r416183b/bin
export PATH=${CLANG_PATH}:${PATH} 
export DTC_EXT=/root/dtc-aosp/dtc 
export CLANG_TRIPLE=aarch64-linux-gnu- 
export CROSS_COMPILE=/root/aarch64-linux-android-4.9/bin/aarch64-linux-android- 
export CROSS_COMPILE_ARM32=/root/arm-linux-androideabi-4.9/bin/arm-linux-androideabi- 
export LD_LIBRARY_PATH=/root/google-clang/clang-r416183b/bin:$LD_LIBRARY_PATH 
make CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out kirisakura_defconfig 
make CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out -j24
```

**Comment by freak07** [comment]
Adjust the buildscript to your system. I suspect you might need to change it so it matches the threads available on your build machine. 

Or it's some other issue with the toolchains. I don't see that error on my end.

**Comment by mxpro1996** [comment]
Replacing -j24 with -j$(nproc --all) can't solve this error.
Would you please tell me which branch toolchains you are using?Actually,I have been busy with this for quite a few days.I will appreciate it if you can tell me!

**Comment by freak07** [comment]
GCC 4.9 for both 64 and 32bit toolchain from googles git. 
Prebuilt clang from Google git as well. The version you can see in my script.

**Comment by SaintZ13** [comment]
> 
> 
> > Error about execvp
> 
> ![IMG_20210517_200704](https://user-images.githubusercontent.com/73088482/118485887-8a8f2800-b74b-11eb-9ff6-84018d5436d6.jpg)
> 
> > Description
> 
> It's been fine before this error.
> 
> > Toolchain (branch android-11.0.0_r12)
> 
> [google-clang](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86)
> [arm-linux-androideabi-4.9](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9)
> [aarch64-linux-android-4.9](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9)
> [aosp-dtc](https://github.com/xzr467706992/dtc-aosp)
> 
> > Config
> 
> ```
> mkdir -p out 
> export ARCH=arm64 
> export SUBARCH=arm64
> export CLANG_PATH=/root/google-clang/clang-r416183b/bin
> export PATH=${CLANG_PATH}:${PATH} 
> export DTC_EXT=/root/dtc-aosp/dtc 
> export CLANG_TRIPLE=aarch64-linux-gnu- 
> export CROSS_COMPILE=/root/aarch64-linux-android-4.9/bin/aarch64-linux-android- 
> export CROSS_COMPILE_ARM32=/root/arm-linux-androideabi-4.9/bin/arm-linux-androideabi- 
> export LD_LIBRARY_PATH=/root/google-clang/clang-r416183b/bin:$LD_LIBRARY_PATH 
> make CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out kirisakura_defconfig 
> make CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out -j24
> ```

I would like to throw in that I have had this issue myself. After extensive researching and trying to figure it out. I went about changing my build environment completely from Ubuntu 20.04 back to 18.04 and that seemed to have solved any building issues.

I suspect there are some dependencies Ubuntu 18.04 has that Ubuntu 20.04 doesn't contain or allow when installing them.
